var express       = require('express')
var swig          = require('swig')
var reactRenderer = require('./middleware/reactRenderer')
var webpack       = require('./middleware/webpack')
var logStart      = require('./logStart')
var path          = require('path')

express()
  .engine('html', swig.renderFile)
  .set('views', path.resolve(__dirname, '../public'))
  .use(webpack)
  .use(reactRenderer)
  .listen(3000, logStart)
