var express       = require('express')
var swig          = require('swig')
var reactRenderer = require('./middleware/reactRenderer')
var webpack       = require('./middleware/webpack')
var logStart      = require('./logStart')
var path          = require('path')
var viewsPath     = path.resolve(process.cwd(), 'browser')
var assetPath     = path.resolve(process.cwd(), 'app/assets')

express()
  .engine('html', swig.renderFile)
  .set('views', viewsPath)
  .use(webpack)
  .use(express.static(assetPath))
  .use(reactRenderer)
  .listen(3000, logStart)
